# Generated by Django 5.2.9 on 2025-12-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(default='Brand', max_length=100)),
                ('model', models.CharField(default='Model', max_length=100)),
                ('location', models.CharField(default='Location', max_length=255)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('mac_address', models.CharField(default='00:00:00:00:00:00', max_length=17)),
                ('manufacture_date', models.CharField(default='1900-00-00', max_length=100)),
                ('comments', models.TextField(blank=True, default='Comments', null=True)),
            ],
        ),
    ]
